### ISSUE TITLE
Custom Slider 적용 및 Todo Edit 구현

### ISSUE THREAD

**Issue by SeBin-Kwon** [SeBin-Kwon/TodoBiny#4]
## 📝 작업 목적 

- 커스텀 슬라이더 적용
- Todo 수정 구현
- Todo 추가/수정 글자 수 제한
- 키보드 다른 곳 눌렀을 때 내려가기
- 진행률별 색상 변화 기능 구현

---

### 🛠️ Tasks

* [x] 커스텀 슬라이더 적용
* [x] TodoDetailView 생성
* [x] Todo 수정 구현
* [x] Todo 추가/수정 글자 수 제한
* [x] 키보드 다른 곳 눌렀을 때 내려가기
* [x] 진행률별 색상 변화 기능 구현
