### ISSUE TITLE
Complete DoneView, DetailView and Develop animation

### ISSUE THREAD

**Issue by SeBin-Kwon** [SeBin-Kwon/TodoBiny#9]
## 📝 작업 목적 

- DoneView와 DetailView의 디자인 및 기능을 완성
- 완료 이펙트 구현
---

### 🛠️ Tasks

- [ ] DoneView 완성
    - [ ] item DetailView와 연결
    - [ ] item 삭제
    - [ ] item DoView로 이동
    - [ ] item 수정
- [ ] 완료 이펙트 구현(애니메이션)
- [ ] 디테일뷰 날짜별 진행률 기록
- [ ] DetailView 완성
- [ ] 애니메이션 디벨롭
